services:
  - type: web
    name: volens
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18

